name: build-cups-docker
run-name: Building CUPS docker image and pushing it to GitHub registry
on:
  push:
    branches:
      - master
    paths:
      - "cups/**"
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      # Checkout step usually not needed when using docker/build-push-action@v6, but necessary for using the relative paths in order to find the correct Dockerfile.
      - name: Checkout repo
        uses: actions/checkout@v4      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx # Needed by docker/build-push-action@v6 
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./cups
          file: ./cups/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
